spring.application.name=Customer Management Application

# JDBC Properties
spring.datasource.url = jdbc:mysql://localhost:3306/customer_management_application
spring.datasource.username = springstudent
spring.datasource.password = springstudent

logging.level.org.springframework.security=DEBUG